openapi: 3.0.0
info:
  title: Nexus API Documentation
  description: API documentation for the Nexus website providing news, live channels, and radio shows.
  version: 1.0.0
servers:
  - url: https://noahabebe.github.io/Nexus/
paths:
  /news:
    get:
      summary: Get news articles
      description: Returns a list of news articles.
      parameters:
        - name: country
          in: query
          description: Filter news articles by country.
          required: false
          schema:
            type: string
      responses:
        '200':
          description: A JSON array of news articles.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/NewsArticle'
  /live-channels:
    get:
      summary: Get live channels
      description: Returns a list of available live channels.
      responses:
        '200':
          description: A JSON array of live channels.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/LiveChannel'
  /radio-shows:
    get:
      summary: Get radio shows
      description: Returns a list of available radio shows.
      responses:
        '200':
          description: A JSON array of radio shows.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RadioShow'
  /countries:
    get:
      summary: Get countries data
      description: Returns data about different countries.
      responses:
        '200':
          description: A JSON object containing countries data.
          content:
            application/json:
              schema:
                type: object
  /news-data:
    get:
      summary: Get news data
      description: Returns data about news articles.
      responses:
        '200':
          description: A JSON object containing news data.
          content:
            application/json:
              schema:
                type: object
  /news-headlines:
    get:
      summary: Get news headlines
      description: Returns headlines of news articles.
      responses:
        '200':
          description: A JSON object containing news headlines.
          content:
            application/json:
              schema:
                type: object
  /sources-data:
    get:
      summary: Get sources data
      description: Returns data about news sources.
      responses:
        '200':
          description: A JSON array of news sources.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/NewsSource'
components:
  schemas:
    NewsArticle:
      type: object
      properties:
        title:
          type: string
        author:
          type: string
        publishedAt:
          type: string
        content:
          type: string
    LiveChannel:
      type: object
      properties:
        name:
          type: string
        url:
          type: string
        logo:
          type: string
        region:
          type: string
    RadioShow:
      type: object
      properties:
        title:
          type: string
        host:
          type: string
        schedule:
          type: string
        description:
          type: string
    NewsSource:
      type: object
      properties:
        name:
          type: string
        url:
          type: string
